### ISSUE TITLE
感谢提供思路，请问实际使用下性能评测是多少呀？

### ISSUE THREAD

**Issue by Waawww** [banmajio/RTSPtoRTMP#12]
作者应该是有实际生成使用，如果使用java来调ffmpeg去转码，单机部署的情况下，大量设备同时进行转码流地址，是否会出现性能上的问题呀？
比如100-200台设备，同时转码，且长期保持。
我目前就是在犹豫是用java自己来转，还是用成熟框架ZLMediaKit
如果方便分享，不胜感激。

**Comment by nn200433** [comment]
上 [wvp-GB28181-pro](https://github.com/648540858/wvp-GB28181-pro) 吧

**Comment by nn200433** [comment]
> 作者应该是有实际生成使用，如果使用java来调ffmpeg去转码，单机部署的情况下，大量设备同时进行转码流地址，是否会出现性能上的问题呀？ 比如100-200台设备，同时转码，且长期保持。 我目前就是在犹豫是用java自己来转，还是用成熟框架ZLMediaKit 如果方便分享，不胜感激。

上 [wvp-GB28181-pro](https://github.com/648540858/wvp-GB28181-pro) 吧
有 [docker](https://github.com/SaltFish001/wvp_pro_compose) 部署，找一下。

**Comment by ghost** [comment]
> 作者应该是有实际生成使用，如果使用java来调ffmpeg去转码，单机部署的情况下，大量设备同时进行转码流地址，是否会出现性能上的问题呀？ 比如100-200台设备，同时转码，且长期保持。 我目前就是在犹豫是用java自己来转，还是用成熟框架ZLMediaKit 如果方便分享，不胜感激。

建议使用zlmediakit  docker安装也很方便

**Comment by Waawww** [comment]
谢谢，经过考虑，还是不进行大量设备的同时转码吧，我们有其他产品用的wvp-GB28181-pro，性能上的麻烦很多。还是单个摄像头转吧。
没有首选zlmediakit，是因为需求只是为了让rtsp的流在web端播放，所以我觉得没必用它。

**Comment by nn200433** [comment]
> 谢谢，经过考虑，还是不进行大量设备的同时转码吧，我们有其他产品用的wvp-GB28181-pro，性能上的麻烦很多。还是单个摄像头转吧。 没有首选zlmediakit，是因为需求只是为了让rtsp的流在web端播放，所以我觉得没必用它。

不差钱用 [模拟不卡](https://m7s.live/) 。巨轻量

**Comment by Waawww** [comment]
> > 谢谢，经过考虑，还是不进行大量设备的同时转码吧，我们有其他产品用的wvp-GB28181-pro，性能上的麻烦很多。还是单个摄像头转吧。 没有首选zlmediakit，是因为需求只是为了让rtsp的流在web端播放，所以我觉得没必用它。
> 
> 不差钱用 [模拟不卡](https://m7s.live/) 。巨轻量

haha，谢谢了，我这小项目就凑合用吧...那个产品正在重构...
